theme: jekyll-theme-cayman
title: Machine Learning Notes
description: Bookmark this to keep an eye on my project updates!
gems:
  - jemoji
  - jekyll-relative-links
markdown: kramdown
github_username: vamshidhar-thonti